#!/bin/bash
# ML-Master: Initialize session with HCC files
# Creates L1/L2 files from templates and displays L3 wisdom

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TEMPLATE_DIR="${SCRIPT_DIR}/../templates"
WISDOM_DIR="${SCRIPT_DIR}/../wisdom"
DATE=$(date +%Y-%m-%d)
TIMESTAMP=$(date "+%Y-%m-%d %H:%M")

echo "=== ML-Master: Session Initialization ==="
echo ""

# Create execution_trace.md (L1)
if [ ! -f "execution_trace.md" ]; then
    if [ -f "$TEMPLATE_DIR/execution_trace.md" ]; then
        sed "s/\[Phase Name\]/Phase 1/g; s/\[Timestamp\]/$TIMESTAMP/g" "$TEMPLATE_DIR/execution_trace.md" > execution_trace.md
        echo "Created: execution_trace.md (L1 - Working Memory)"
    else
        cat > execution_trace.md << EOF
# Execution Trace

## Current Phase: Phase 1
## Started: $TIMESTAMP

## Operations Log
| Timestamp | Action | Output Summary |
|-----------|--------|----------------|

## Code Patches

## Terminal Outputs

## Observations

EOF
        echo "Created: execution_trace.md (L1 - Working Memory)"
    fi
else
    echo "Exists: execution_trace.md"
fi

# Create task_plan.md (L2)
if [ ! -f "task_plan.md" ]; then
    if [ -f "$TEMPLATE_DIR/task_plan.md" ]; then
        cp "$TEMPLATE_DIR/task_plan.md" task_plan.md
        echo "Created: task_plan.md (L2 - Strategic State)"
    else
        cat > task_plan.md << 'EOF'
# Task Plan: [Title]

## Strategic Goal
[One sentence describing the end state]

## Plan Tree

### Direction 1: [Direction Name]

- **Implementation 1.1**: [Step]
  - Status: `in_progress`
  - Outcome:

## Current Focus
- Direction: 1
- Implementation: 1.1
- Status: `in_progress`

## Key Decisions
| Decision | Rationale | Date |
|----------|-----------|------|

## Blockers & Risks
| Blocker/Risk | Mitigation | Status |
|--------------|------------|--------|
EOF
        echo "Created: task_plan.md (L2 - Strategic State)"
    fi
else
    echo "Exists: task_plan.md"
fi

# Create findings.md (L2)
if [ ! -f "findings.md" ]; then
    if [ -f "$TEMPLATE_DIR/findings.md" ]; then
        cp "$TEMPLATE_DIR/findings.md" findings.md
        echo "Created: findings.md (L2 - Strategic Memory)"
    else
        cat > findings.md << 'EOF'
# Findings & Strategic Memory

## Key Insights
-

## Validated Hypotheses
| Hypothesis | Validation | Conclusion |
|------------|------------|------------|

## Failed Attempts
| Attempt | Why Failed | Lesson |
|---------|------------|--------|

## Experiment Results
| Experiment | Parameters | Metrics | Notes |
|------------|------------|---------|-------|

## Technical Decisions
| Decision | Rationale |
|----------|-----------|

## Resources
-
EOF
        echo "Created: findings.md (L2 - Strategic Memory)"
    fi
else
    echo "Exists: findings.md"
fi

echo ""
echo "=== L3 Wisdom (Prior Knowledge) ==="

# Create CLAUDE.md for project context (auto Context Hit)
if [ ! -f "CLAUDE.md" ]; then
    cat > CLAUDE.md << 'EOF'
# Project Context (ML-Master)

## ⚠️ BEFORE YOU START - MUST READ
1. **Read `task_plan.md`** - Get the Strategic Goal and current plan
2. **Read `findings.md`** - Check Key Insights and Failed Attempts
3. **THEN start working** - Don't skip step 1 and 2!

> This summary may be STALE. Always verify by reading actual files.

---

## Current State (sync'd on /promote)
- **Goal**: _Set via task_plan.md after /plan_
- **Best Code**: _Updated after experiments_

## Memory Files
| File | Layer | Content |
|------|-------|---------|
| `task_plan.md` | L2 | Strategic Goal, Research Plan, Best Code |
| `findings.md` | L2 | Key Insights, Failed Attempts, Experiment Results |
| `execution_trace.md` | L1 | Current phase operations (cleared on /promote) |

## Quick Commands
| Command | Action |
|---------|--------|
| `/status` | View current state |
| `/promote` | Compress L1→L2, sync this file |
| `/recover` | Restore context after /clear |
| `/complete` | Finish task, P2 Promotion to L3 |

## Rules
1. **5-Action Rule**: Update `execution_trace.md` every 5 Write/Edit/Bash
2. **Best Code Tracking**: Update `task_plan.md` when metrics improve
3. **Dual Write**: Execution details→L1, Conclusions→L2

## ⚠️ After /clear
**IMMEDIATELY run `/recover`** before doing anything else!
Your conversation history is gone, but L2 files still have the context.

---
*Auto-generated by ML-Master. This file is auto-synced on /promote and /complete.*
EOF
    echo "Created: CLAUDE.md (Project Context for auto Context Hit)"
else
    echo "Exists: CLAUDE.md"
fi

# Display relevant wisdom
if [ -f "$WISDOM_DIR/global_wisdom.md" ]; then
    echo ""
    echo "Loading ML best practices from L3..."
    echo ""
    # Show key sections
    echo "[Common Errors & Solutions]"
    sed -n '/## Common Errors & Solutions/,/^##/p' "$WISDOM_DIR/global_wisdom.md" | head -15
    echo ""
    echo "[Hyperparameter Starting Points]"
    sed -n '/## Hyperparameter Starting Points/,/^##/p' "$WISDOM_DIR/global_wisdom.md" | head -10
    echo ""
    echo "Full wisdom available at: wisdom/global_wisdom.md"
else
    echo "WARNING: L3 wisdom not found at $WISDOM_DIR/global_wisdom.md"
fi

# Context Prefetching: Search for similar task wisdom
TASK_DESCRIPTOR="${1:-}"
if [ -n "$TASK_DESCRIPTOR" ] && [ -f "$WISDOM_DIR/embedding_utils.py" ]; then
    echo ""
    echo "=== Context Prefetching (L3 → Context) ==="
    echo "Searching for similar task wisdom..."
    echo ""

    # 检测 Python 环境: 优先使用 uv run，然后 python3
    PYTHON_CMD=""
    if [ -f "pyproject.toml" ] && command -v uv &> /dev/null; then
        PYTHON_CMD="uv run python"
    elif command -v python3 &> /dev/null; then
        PYTHON_CMD="python3"
    fi

    if [ -n "$PYTHON_CMD" ]; then
        SIMILAR_WISDOM=$($PYTHON_CMD "$WISDOM_DIR/embedding_utils.py" search "$TASK_DESCRIPTOR" 2>/dev/null || echo "[]")

        if [ "$SIMILAR_WISDOM" != "[]" ] && [ -n "$SIMILAR_WISDOM" ]; then
            echo "Found similar tasks:"
            echo "$SIMILAR_WISDOM"
            echo ""
            echo "Review the referenced wisdom files for relevant insights."
        else
            echo "No similar task wisdom found in L3 index."
            echo "This will be the first task of its kind!"
        fi
    else
        echo "WARNING: No Python environment found, skipping context prefetching"
        echo "Install python3 or use 'uv init' to create a virtual environment"
    fi
elif [ -z "$TASK_DESCRIPTOR" ]; then
    echo ""
    echo "TIP: Run with task description for context prefetching:"
    echo "  init-session.sh \"your task description here\""
fi

echo ""
echo "=== Initialization Complete ==="
echo ""
echo "Files created:"
echo "  - execution_trace.md (L1 - clear after each phase)"
echo "  - task_plan.md (L2 - persistent plan)"
echo "  - findings.md (L2 - accumulated knowledge)"
echo "  - CLAUDE.md (Project context for auto Context Hit)"
echo ""
echo "Next steps:"
echo "1. Update task_plan.md with your Strategic Goal"
echo "2. Define your Plan Tree (Directions → Implementations)"
echo "3. Start executing first Implementation"
echo "4. Remember: Update L1 every 5 tool calls (5-Action Rule)"
echo ""
